variables:
    REPOSITORY_URL: "https://lamtruong:$TOKEN@git.myg.vn/telegam/server-game-fap-ton.git"

    STAGE: "/home/flappy/dev-api.flappy"
    PRODUCT: "/home/flappy/live-api.flappy"
    
    PM2_NAME: "server-game-fap-ton:5005"
    CLONE_TMP: "/home/gitlab-runner/server-game-fap-ton"

stages:
    - build_STAGE
    - build_PRODUCT
    - deploy_STAGE
    - deploy_PRODUCT
    - checklog_STAGE
    - checklog_PRODUCT

build_STAGE:
    stage: build_STAGE
    variables:
        GIT_STRATEGY: none
    before_script:
        - if [ ! -d "$STAGE" ]; then mkdir -p "$STAGE"; fi
        - cd $STAGE
        - if pm2 describe $PM2_NAME > /dev/null 2>&1; then pm2 stop $PM2_NAME; fi
        - if [ -d "$STAGE" ]; then find "$STAGE" -mindepth 1 -path "$STAGE/node_modules" -prune -o -name ".env" -prune -o -exec rm -rf {} +; fi
        - if [ -d "$CLONE_TMP" ]; then rm -rf "$CLONE_TMP"; fi
        - if [ -d $STAGE/node_modules ]; then cd /home/gitlab-runner/ && git clone --branch stage $REPOSITORY_URL && cd $CLONE_TMP && mv * $STAGE && rm -rf $CLONE_TMP; else git clone --branch stage $REPOSITORY_URL $STAGE; fi
    script:
        - cd $STAGE
        - npm install
    tags:
        - flappy
    only:
        - stage

build_PRODUCT:
    stage: build_PRODUCT
    variables:
        GIT_STRATEGY: none
    script:
        - if [ ! -d "$PRODUCT" ]; then sudo mkdir -p "$PRODUCT"; fi
        - cd $PRODUCT
        - if pm2 describe $PM2_NAME > /dev/null 2>&1; then pm2 stop $PM2_NAME; fi
        - if [ -d "$PRODUCT" ]; then find "$PRODUCT" -mindepth 1 -path "$PRODUCT/node_modules" -prune -o -name ".env" -prune -o -exec rm -rf {} +; fi
        - if [ -d "$CLONE_TMP" ]; then rm -rf "$CLONE_TMP"; fi
        - if [ -d $PRODUCT/node_modules ]; then cd /home/gitlab-runner/ && git clone --branch product $REPOSITORY_URL && cd $CLONE_TMP && mv * $PRODUCT && rm -rf $CLONE_TMP; else git clone --branch product $REPOSITORY_URL $PRODUCT; fi
        - cd $PRODUCT
        - npm install
        - sudo chown -R flappy. $PRODUCT
    tags:
        - flappy-live
    only:
        - product

deploy_STAGE:
    stage: deploy_STAGE
    variables:
        GIT_STRATEGY: none
    script:
        - cd $STAGE
        - pm2 restart start.config.js
    tags:
        - flappy
    only:
        - stage

deploy_PRODUCT:
    stage: deploy_PRODUCT
    variables:
        GIT_STRATEGY: none
    script:
        - su flappy -c "cd $PRODUCT; pm2 restart start.config.js"
    tags:
        - flappy-live
    only:
        - product

checklog_STAGE:
    stage: checklog_STAGE
    variables:
        GIT_STRATEGY: none
    script:
        - cd $STAGE
        - timeout 5 pm2 logs $PM2_NAME || true
    tags:
        - flappy
    only:
        - stage

checklog_PRODUCT:
    stage: checklog_PRODUCT
    variables:
        GIT_STRATEGY: none
    script:
        - su flappy -c "cd $PRODUCT; timeout 5 pm2 logs $PM2_NAME || true"
    tags:
        - flappy-live
    only:
        - product
